---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: sunatcpe-db
      app: sunatcpe-db
    name: sunatcpe-db
  spec:
    ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      service: sunatcpe-db
      app: sunatcpe-db
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: sunatcpe-db
    name: sunatcpe-db-postgresql-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: sunatcpe-db
      app: sunatcpe-db
    name: sunatcpe-db
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: sunatcpe-db
    strategy:
      rollingParams:
        timeoutSeconds: 7200
      type: Rolling
    template:
      metadata:
        labels:
          service: sunatcpe-db
          app: sunatcpe-db
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            value: sunatcpe
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                key: db.user
                name: sunatcpe
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db.password
                name: sunatcpe
          - name: POSTGRESQL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db.admin.password
                name: sunatcpe
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          image: registry.centos.org/postgresql/postgresql:9.6
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            failureThreshold: 6
            initialDelaySeconds: 60
            timeoutSeconds: 5
          name: sunatcpe-db
          ports:
          - containerPort: 5432
            name: postgresql
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: sunatcpe-db-postgresql-data
            readOnly: false
        volumes:
        - name: sunatcpe-db-postgresql-data
          persistentVolumeClaim:
            claimName: sunatcpe-db-postgresql-data
    triggers:
    - type: ConfigChange
